version: "3.2"
services:
  nodejs:
    image: conglt/study-chain-server
    volumes:
      - ./:/app
    environment:
      - MONGODB_CONTAINER=${MONGODB_CONTAINER}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
