# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer.certificate.com:
    container_name: orderer.certificate.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/certificate.com/orderers/orderer.certificate.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/certificate.com/orderers/orderer.certificate.com/tls/:/var/hyperledger/orderer/tls
      - orderer.certificate.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.academy.certificate.com:
    container_name: peer0.academy.certificate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.academy.certificate.com
      - CORE_PEER_ADDRESS=peer0.academy.certificate.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.academy.certificate.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.academy.certificate.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.academy.certificate.com:7051
      - CORE_PEER_LOCALMSPID=AcademyMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/academy.certificate.com/peers/peer0.academy.certificate.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/academy.certificate.com/peers/peer0.academy.certificate.com/tls:/etc/hyperledger/fabric/tls
      - peer0.academy.certificate.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.academy.certificate.com:
    container_name: peer1.academy.certificate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.academy.certificate.com
      - CORE_PEER_ADDRESS=peer1.academy.certificate.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.academy.certificate.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.academy.certificate.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.academy.certificate.com:7051
      - CORE_PEER_LOCALMSPID=AcademyMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/academy.certificate.com/peers/peer1.academy.certificate.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/academy.certificate.com/peers/peer1.academy.certificate.com/tls:/etc/hyperledger/fabric/tls
      - peer1.academy.certificate.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.student.certificate.com:
    container_name: peer0.student.certificate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.student.certificate.com
      - CORE_PEER_ADDRESS=peer0.student.certificate.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.student.certificate.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.student.certificate.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.student.certificate.com:10051
      - CORE_PEER_LOCALMSPID=StudentMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/student.certificate.com/peers/peer0.student.certificate.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/student.certificate.com/peers/peer0.student.certificate.com/tls:/etc/hyperledger/fabric/tls
      - peer0.student.certificate.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.student.certificate.com:
    container_name: peer1.student.certificate.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.student.certificate.com
      - CORE_PEER_ADDRESS=peer1.student.certificate.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.student.certificate.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.student.certificate.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.student.certificate.com:9051
      - CORE_PEER_LOCALMSPID=StudentMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/student.certificate.com/peers/peer1.student.certificate.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/student.certificate.com/peers/peer1.student.certificate.com/tls:/etc/hyperledger/fabric/tls
      - peer1.student.certificate.com:/var/hyperledger/production
    ports:
      - 10051:10051
